# extract_references.R
# TITLE:          extract citations from BOW reference web page to data frame and csv files
# AUTHORS:        Pat Bills
# COLLABORATORS:  Phoebe Zarnetske, Kelly Kapsar, Emily Parker
# DATA INPUT:     Data entry CSV files in L0 folder
# DATA OUTPUT:    L0 combined data: AvianInteractionData_L0.csv
# PROJECT:        Avian Interaction Database
# DATE:           July 2025
# NOTES:          currently a proof of concept not used in workflow


library(rvest)
library(stringr)
library(readr)


#' convert HTML refs to CSV
#' given a BOW references page downloaded as HTML
#' create a data frame of all of the references that are on
#' that HTML.
#' @param path_to_html_file location of the file saved as html from BOW page
#' @example:
#' refs.df <- refs2df("../species/refs/Falco_mexicanus.references.html")
#' readr::write_csv(refs.df, "../species/refs/Falco_mexicanus.references.csv")
#' 
refs2df <- function(path_to_html_file){
    # Read the HTML file
    html <- rvest::read_html(path_to_html_file)
    # Extract all <li> elements with an id starting with "REF"
    refs <- html %>%
    rvest::html_elements("li[id^='REF']")
    # Parse reference number and citation
    data <- lapply(refs, function(ref) {
    text <- rvest::html_text(ref)
    # Match reference number followed by a dot and space
    match <- str_match(text, "^\\s*(\\d+)\\.\\s*(.*)$")
    ref_num <- match[2]
    citation <- match[3]
    list(reference_number = ref_num, citation = citation)
    })

    # Convert to data frame
    references.df <- do.call(rbind, lapply(data, as.data.frame))
    colnames(references.df) <- c("reference_number", "citation")
    return(references.df)
}

#' get citation numbers 
#' given some text copied out of BOW, with numbered references like (34,34)
#' connect those to the references from BOW using a reference data frame generated by 
#' the function above refs2df()
#' @param paragraph character some plain text chunk of text from BOW with numbered refs in it
#' @param references.df a reference file corresponding to the BOW species account, created using refs2df()
#' @returns character delimited list of citations for that pararaph, rather than just the numbers
#' 
extract_citations_numbers_from_text <- function(paragraph, references.df) {
  # Extract all numbers in parentheses, possibly separated by commas, sometimes has colon
  matches <- stringr::str_extract_all(paragraph, "(?<=\\()[0-9,\\s]+(?=\\))")[[1]]
  ref_nums <- unique(unlist(str_split(matches, ","))) |> stringr::str_trim()
  # ref_nums <- str_trim(ref_nums)
  # Remove any non-numeric entries but leave as strings
  ref_nums <- ref_nums[str_detect(ref_nums, "^\\d+$")]

  # Lookup citations
  references.selected.df <- references.df[references.df$reference_number %in% ref_nums,]
  # Concatenate with pipe
  result <- paste(references.selected.df$citation, collapse = " | ")
  return(result)
}
