---
title: "The Avian Interaction Database"
subtitle: "A project from the [SpaCE Lab](https://www.communityecologylab.com/)"
format: html
editor: visual
title-block-banner: images/bird-telephone-banner.jpg
---

## 

::: {style="text-align: center"}
## Developing the most complete network of interactions among the birds of the Western Hemisphere.
:::

::: {style="margin-bottom: 5rem;"}
Blurb about the project.
:::


::: {style="display: flex; justify-content: space-between; gap: 2rem;"}

<div style="flex: 1;">

**Most recent bird species added!**

```{r}
#| echo: false
#| warning: false
#| message: false
#| fig-width: 4
#| fig-height: 4
library(jsonlite)
library(readr)
source("code/avicommons_clem.r")
avi <- jsonlite::fromJSON("code/avicommons_full.json")
clem <- readr::read_csv("code/clemtax_2025.csv")
info1 <- get_avicommons_image("Electron platyrhynchum", size = 480)
plot_avicommons_image(info1)
```

</div> <div style="flex: 1;">

**Species with highest number of interactions!**

```{r}
#| echo: false
#| warning: false
#| message: false
#| fig-width: 4
#| fig-height: 4

info2 <- get_avicommons_image("Querula purpurata", size = 480)
plot_avicommons_image(info2)
```

</div>
  
  
:::


